from django.urls import path
from . import views


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("reports/attendance-query/", views.attendance_query_report, name="attendance_query_report"),
    path("reports/schedules/", views.schedule_report, name="schedule_report"),
    path("supervisors/", views.supervisor_list, name="supervisor_list"),
    path("supervisors/add/", views.supervisor_add, name="supervisor_add"),
    path("supervisors/edit/<int:id>/", views.supervisor_edit, name="supervisor_edit"),
    path("supervisors/delete/<int:id>/", views.supervisor_delete, name="supervisor_delete"),
    path("guards/", views.guard_list, name="guard_list"),
    path("guards/add/", views.guard_add, name="guard_add"),
    path("guards/edit/<int:id>/", views.guard_edit, name="guard_edit"),
    path("guards/delete/<int:id>/", views.guard_delete, name="guard_delete"),
    path("clients/", views.client_list, name="client_list"),
    path("clients/add/", views.client_add, name="client_add"),
    path("clients/edit/<int:id>/", views.client_edit, name="client_edit"),
    path("clients/delete/<int:id>/", views.client_delete, name="client_delete"),
    path("deployments/", views.deployment_list, name="deployment_list"),
    path("deployments/program-guard/", views.program_guard, name="program_guard"),
    path("deployments/add/", views.deployment_add, name="deployment_add"),
    path("deployments/edit/<int:id>/", views.deployment_edit, name="deployment_edit"),
    path("deployments/delete/<int:id>/", views.deployment_delete, name="deployment_delete"),
    path("assets/", views.asset_list, name="asset_list"),
    path("assets/add/", views.asset_add, name="asset_add"),
    path("assets/edit/<int:id>/", views.asset_edit, name="asset_edit"),
    path("assets/delete/<int:id>/", views.asset_delete, name="asset_delete"),
    path("attendance/", views.attendance_list, name="attendance_list"),
    path("attendance/add/", views.attendance_add, name="attendance_add"),
    path("attendance/edit/<int:id>/", views.attendance_edit, name="attendance_edit"),
    path("attendance/delete/<int:id>/", views.attendance_delete, name="attendance_delete"),
    path("shifts/", views.shift_list, name="shift_list"),
    path("shifts/import/", views.shift_import, name="shift_import"),
    path("shifts/add/", views.shift_add, name="shift_add"),
    path("shifts/edit/<int:id>/", views.shift_edit, name="shift_edit"),
    path("shifts/delete/<int:id>/", views.shift_delete, name="shift_delete"),
    path("salaries/", views.salary_list, name="salary_list"),
    path("salaries/add/", views.salary_add, name="salary_add"),
    path("salaries/edit/<int:id>/", views.salary_edit, name="salary_edit"),
    path("salaries/delete/<int:id>/", views.salary_delete, name="salary_delete"),
    path("incidents/", views.incident_list, name="incident_list"),
    path("incidents/add/", views.incident_add, name="incident_add"),
    path("incidents/edit/<int:id>/", views.incident_edit, name="incident_edit"),
    path("incidents/delete/<int:id>/", views.incident_delete, name="incident_delete"),
    path("disciplinary-actions/", views.disciplinary_action_list, name="disciplinary_action_list"),
    path("disciplinary-actions/add/", views.disciplinary_action_add, name="disciplinary_action_add"),
    path("disciplinary-actions/edit/<int:id>/", views.disciplinary_action_edit, name="disciplinary_action_edit"),
    path("disciplinary-actions/delete/<int:id>/", views.disciplinary_action_delete, name="disciplinary_action_delete"),
    path("advance-requests/", views.advance_request_list, name="advance_request_list"),
    path("advance-requests/add/", views.advance_request_add, name="advance_request_add"),
    path("advance-requests/edit/<int:id>/", views.advance_request_edit, name="advance_request_edit"),
    path("advance-requests/delete/<int:id>/", views.advance_request_delete, name="advance_request_delete"),
]
