# Generated by Django 6.0.1 on 2026-05-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('guard_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('date_of_joining', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('deployment_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='guardmanagementsystem.client')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='guardmanagementsystem.guard')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave')], default='Present', max_length=20)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='guardmanagementsystem.guard')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Returned', 'Returned')], default='Available', max_length=20)),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='guardmanagementsystem.guard')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='guardmanagementsystem.guard')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('shift_type', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Weekend', 'Weekend'), ('Public Holiday', 'Public Holiday')], max_length=30)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='guardmanagementsystem.guard')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('guard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardmanagementsystem.guard')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField()),
                ('incident_type', models.CharField(choices=[('Theft', 'Theft'), ('Fight', 'Fight'), ('Accident', 'Accident'), ('Fire', 'Fire'), ('Security Breach', 'Security Breach'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='guardmanagementsystem.guard')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='guardmanagementsystem.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('disciplinary_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateField()),
                ('action_type', models.CharField(choices=[('Warning', 'Warning'), ('Suspension', 'Suspension'), ('Fine', 'Fine'), ('Dismissal', 'Dismissal'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('penalty', models.CharField(blank=True, max_length=200, null=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='guardmanagementsystem.guard')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_disciplinary_actions', to='guardmanagementsystem.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('advance_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='guardmanagementsystem.guard')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advance_requests', to='guardmanagementsystem.supervisor')),
            ],
        ),
    ]
