# Generated by Django 6.0.1 on 2026-05-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='employee_type',
            field=models.CharField(choices=[('Guard', 'Guard'), ('Supervisor', 'Supervisor')], default='Guard', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='guardmanagementsystem.supervisor'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='guardmanagementsystem.guard'),
        ),
    ]
