# Generated by Django 6.0.1 on 2026-05-20 21:25

import guardmanagementsystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0002_salary_employee_type_salary_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='attendance_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='computed_from_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(default=guardmanagementsystem.models.current_year),
        ),
    ]
