# Generated by Django 6.0.1 on 2026-05-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0003_guard_daily_rate_salary_attendance_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=10500, max_digits=12),
        ),
        migrations.AlterField(
            model_name='guard',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=7000, max_digits=12),
        ),
    ]
