# Generated by Django 6.0.1 on 2026-05-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0004_supervisor_daily_rate_alter_guard_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='replacement_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_attendances', to='guardmanagementsystem.guard'),
        ),
    ]
