# Generated by Django 6.0.1 on 2026-05-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0005_attendance_absence_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='employee_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='employee_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
