# Generated by Django 6.0.1 on 2026-05-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0006_guard_employee_number_supervisor_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('Day', 'D'), ('Night', 'N'), ('Weekend', 'D/N'), ('Public Holiday', 'PH')], max_length=30),
        ),
    ]
