# Generated by Django 6.0.1 on 2026-05-21 08:11

from django.db import migrations, models


def convert_shift_types_to_codes(apps, schema_editor):
    Shift = apps.get_model('guardmanagementsystem', 'Shift')
    shift_type_map = {
        'Day': 'D',
        'O': 'D',
        'Night': 'N',
        'Weekend': 'D/N',
        'Day/Night': 'D/N',
        'Public Holiday': 'PH',
        'Public_Holiday': 'PH',
        'Holiday': 'PH',
    }

    for old_value, new_value in shift_type_map.items():
        Shift.objects.filter(shift_type=old_value).update(shift_type=new_value)


def convert_shift_codes_to_old_values(apps, schema_editor):
    Shift = apps.get_model('guardmanagementsystem', 'Shift')
    shift_type_map = {
        'D': 'Day',
        'N': 'Night',
        'D/N': 'Weekend',
        'PH': 'Public Holiday',
    }

    for old_value, new_value in shift_type_map.items():
        Shift.objects.filter(shift_type=old_value).update(shift_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0007_alter_shift_shift_type'),
    ]

    operations = [
        migrations.RunPython(convert_shift_types_to_codes, convert_shift_codes_to_old_values),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('D', 'D'), ('N', 'N'), ('D/N', 'D/N'), ('PH', 'PH')], max_length=30),
        ),
    ]
