# Generated by Django 6.0.1 on 2026-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0008_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='further_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='involved_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='involved_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=10),
        ),
    ]
