# Generated by Django 6.0.1 on 2026-05-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0009_incident_further_comments_incident_incident_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('guard', 'attendance_date'), name='unique_guard_attendance_date'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('guard', 'start_time'), name='unique_guard_shift_date'),
        ),
    ]
