# Generated by Django 6.0.1 on 2026-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0010_attendance_unique_guard_attendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_code', models.CharField(max_length=50, unique=True)),
                ('site_location', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
            ],
        ),
        migrations.AddField(
            model_name='guard',
            name='rfid_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
