# Generated by Django 6.0.1 on 2026-06-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0012_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guard',
            old_name='employee_number',
            new_name='guard_number',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='employee_number',
            new_name='supervisor_number',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='designation',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='deployment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guardmanagementsystem.deployment'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
