# Generated by Django 6.0.1 on 2026-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0013_rename_employee_number_guard_guard_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
