# Generated by Django 6.0.1 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0014_supervisor_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(
                choices=[
                    ('Present', 'Present'),
                    ('Absent', 'Absent'),
                    ('Late', 'Late'),
                    ('On Leave', 'On Leave'),
                ],
                default='Present',
                max_length=20,
            ),
        ),
    ]
