# Generated by Django 6.0.1 on 2026-06-15 05:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_guard_rfid_numbers(apps, schema_editor):
    Guard = apps.get_model('guardmanagementsystem', 'Guard')
    RFIDCard = apps.get_model('guardmanagementsystem', 'RFIDCard')

    for guard in Guard.objects.exclude(rfid_card_number__isnull=True).exclude(rfid_card_number=''):
        card, _ = RFIDCard.objects.get_or_create(
            card_uid=guard.rfid_card_number,
            defaults={
                'card_number': guard.rfid_card_number,
                'status': 'Active',
            },
        )

        if not guard.rfid_card_id:
            guard.rfid_card_id = card.rfid_card_id
            guard.save(update_fields=['rfid_card'])


def clear_guard_rfid_links(apps, schema_editor):
    Guard = apps.get_model('guardmanagementsystem', 'Guard')
    Guard.objects.update(rfid_card=None)


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0015_normalize_attendance_present_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('rfid_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_uid', models.CharField(max_length=100, unique=True)),
                ('card_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lost', 'Lost'), ('Damaged', 'Damaged'), ('Returned', 'Returned')], default='Active', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='guard',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guard',
            name='rfid_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guard', to='guardmanagementsystem.rfidcard'),
        ),
        migrations.RunPython(migrate_guard_rfid_numbers, clear_guard_rfid_links),
    ]
