# Generated by Django 6.0.1 on 2026-06-15 06:35

import django.db.models.deletion
from django.db import migrations, models


def link_devices_to_deployments(apps, schema_editor):
    IoTDevice = apps.get_model('guardmanagementsystem', 'IoTDevice')
    Deployment = apps.get_model('guardmanagementsystem', 'Deployment')

    for device in IoTDevice.objects.exclude(site_location=''):
        deployment = Deployment.objects.filter(
            site_location__iexact=device.site_location,
            status='Active',
        ).order_by('-start_date').first()

        if not deployment:
            deployment = Deployment.objects.filter(
                site_location__iexact=device.site_location,
            ).order_by('-start_date').first()

        if deployment:
            device.deployment_id = deployment.deployment_id
            device.client_id = deployment.client_id
            device.site_location = deployment.site_location
            device.save(update_fields=['deployment', 'client', 'site_location'])


def unlink_devices_from_deployments(apps, schema_editor):
    IoTDevice = apps.get_model('guardmanagementsystem', 'IoTDevice')
    IoTDevice.objects.update(deployment=None, client=None)


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0016_rfidcard_guard_user_supervisor_user_guard_rfid_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_devices', to='guardmanagementsystem.client'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_devices', to='guardmanagementsystem.deployment'),
        ),
        migrations.RunPython(link_devices_to_deployments, unlink_devices_from_deployments),
    ]
