# Generated by Django 6.0.1 on 2026-06-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0017_iotdevice_client_iotdevice_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='swiped_by_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swiped_attendances', to='guardmanagementsystem.supervisor'),
        ),
    ]
