# Generated by Django 6.0.1 on 2026-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0018_attendance_swiped_by_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Dismissed', 'Dismissed'), ('Resigned', 'Resigned')], default='Active', max_length=20),
        ),
    ]
