# Generated by Django 6.0.1 on 2026-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0019_alter_guard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='device_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
