# Generated by Django 6.0.1 on 2026-06-15 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0020_alter_iotdevice_api_key_alter_iotdevice_device_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_guards', to='guardmanagementsystem.supervisor'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='guard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profiles', to='guardmanagementsystem.guard'),
        ),
    ]
