# Generated by Django 6.0.1 on 2026-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0021_guard_supervisor_alter_supervisor_guard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='recovery_period_months',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
