# Generated by Django 6.0.1 on 2026-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0023_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
