# Generated by Django 6.0.1 on 2026-06-16 19:09

import django.db.models.deletion
from django.db import migrations, models


def link_existing_advance_requests(apps, schema_editor):
    AdvanceRequest = apps.get_model('guardmanagementsystem', 'AdvanceRequest')
    Supervisor = apps.get_model('guardmanagementsystem', 'Supervisor')

    for advance_request in AdvanceRequest.objects.select_related('guard__supervisor'):
        supervisor = advance_request.guard.supervisor
        if supervisor:
            advance_request.review_supervisor = supervisor
            advance_request.save(update_fields=['review_supervisor'])

    for supervisor in Supervisor.objects.all():
        supervisor.advance_notifications = AdvanceRequest.objects.filter(
            review_supervisor=supervisor,
            status='Pending',
        ).count()
        supervisor.save(update_fields=['advance_notifications'])


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0024_advancerequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='approval_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='review_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_notifications_requests', to='guardmanagementsystem.supervisor'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='advance_notifications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(link_existing_advance_requests, migrations.RunPython.noop),
    ]
