# Generated by Django 6.0.1 on 2026-06-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0025_advancerequest_approval_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='client_notifications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClientCommunication',
            fields=[
                ('communication_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('Service Request', 'Service Request'), ('Complaint', 'Complaint'), ('Feedback', 'Feedback'), ('Incident Report', 'Incident Report'), ('Communication', 'Communication')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_response', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='guardmanagementsystem.client')),
                ('review_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_communications', to='guardmanagementsystem.supervisor')),
            ],
        ),
    ]
