# Generated by Django 6.0.1 on 2026-06-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0026_supervisor_client_notifications_clientcommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
