# Generated by Django 6.0.1 on 2026-06-17 09:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0027_supervisor_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignmentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(default=datetime.date.today)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('condition_on_return', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='guardmanagementsystem.asset')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignment_history', to='guardmanagementsystem.guard')),
            ],
            options={
                'ordering': ['-assigned_date', '-history_id'],
            },
        ),
    ]
