# Generated by Django 6.0.1 on 2026-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0028_assetassignmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='swiped_by_supervisor',
        ),
        migrations.RemoveField(
            model_name='disciplinaryaction',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='clientcommunication',
            name='review_supervisor',
        ),
        migrations.RemoveField(
            model_name='guard',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='review_supervisor',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='approved_by',
        ),
        migrations.RenameField(
            model_name='clientcommunication',
            old_name='supervisor_response',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee_type',
            field=models.CharField(choices=[('Guard', 'Guard')], default='Guard', max_length=20),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
