# Generated by Django 6.0.1 on 2026-06-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0029_remove_attendance_swiped_by_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcommunication',
            name='client',
        ),
        migrations.RemoveField(
            model_name='disciplinaryaction',
            name='guard',
        ),
        migrations.DeleteModel(
            name='AdvanceRequest',
        ),
        migrations.DeleteModel(
            name='ClientCommunication',
        ),
        migrations.DeleteModel(
            name='DisciplinaryAction',
        ),
    ]
