# Generated by Django 6.0.1 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0031_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Security Services', 'Security Services'), ('Event Security', 'Event Security'), ('Static Guarding', 'Static Guarding'), ('Mobile Patrol', 'Mobile Patrol'), ('Other', 'Other')], default='Security Services', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
