# Generated by Django 6.0.1 on 2026-06-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0032_contract_status_alter_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='guardmanagementsystem.contract'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='guardmanagementsystem.shift'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Running', 'Running'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='DeploymentGuard',
            fields=[
                ('deployment_guard_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_guards', to='guardmanagementsystem.deployment')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_guard_assignments', to='guardmanagementsystem.guard')),
            ],
            options={
                'unique_together': {('deployment', 'guard')},
            },
        ),
    ]
