# Generated by Django 6.0.1 on 2026-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0033_deployment_contract_deployment_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Deployment', 'On Deployment'), ('Available', 'Available'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Running', 'Running'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
