# Generated by Django 6.0.1 on 2026-06-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0034_alter_contract_contract_type_alter_deployment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSwipe',
            fields=[
                ('swipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('swipe_time', models.DateTimeField()),
                ('swipe_type', models.CharField(choices=[('check_in', 'Check In'), ('hourly', 'Hourly Swipe'), ('check_out', 'Check Out'), ('replacement', 'Replacement')], default='hourly', max_length=20)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='guardmanagementsystem.attendance')),
                ('iot_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_swipes', to='guardmanagementsystem.iotdevice')),
            ],
            options={
                'ordering': ['swipe_time', 'swipe_id'],
            },
        ),
    ]
