# Generated by Django 6.0.1 on 2026-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0035_attendanceswipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Event Security', 'Event Security'), ('Static Guarding', 'Static Guarding'), ('Mobile Patrol', 'Mobile Patrol'), ('Other', 'Other')], default='Static Guarding', max_length=100),
        ),
    ]
