# Generated by Django 6.0.1 on 2026-06-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0036_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Deployment', 'On Deployment'), ('Available', 'Available'), ('Has No Deployment', 'Has No Deployment'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Running', 'Running'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
