# Generated by Django 6.0.1 on 2026-06-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0037_alter_deployment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='guard',
        ),
    ]
