# Generated by Django 6.0.1 on 2026-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0038_remove_deployment_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='day_shift_guards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='night_shift_guards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
