# Generated by Django 6.0.1 on 2026-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0039_contract_day_shift_guards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentguard',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Deployment', 'On Deployment'), ('Has No Deployment', 'Has No Deployment'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
