# Generated by Django 6.0.1 on 2026-06-20 12:38

import datetime
from django.db import migrations, models


def copy_start_date_to_deployment_date(apps, schema_editor):
    DeploymentGuard = apps.get_model('guardmanagementsystem', 'DeploymentGuard')
    for assignment in DeploymentGuard.objects.all().only('pk', 'start_date'):
        if assignment.start_date:
            assignment.deployment_date = assignment.start_date
            assignment.save(update_fields=['deployment_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0040_deploymentguard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentguard',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymentguard',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymentguard',
            name='deployment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(copy_start_date_to_deployment_date, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='deploymentguard',
            unique_together={('deployment', 'guard', 'deployment_date')},
        ),
        migrations.RemoveField(
            model_name='deploymentguard',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='deploymentguard',
            name='start_date',
        ),
    ]