# Generated by Django 6.0.1 on 2026-06-20 12:51

from django.db import migrations, models


def update_guard_deployment_status_labels(apps, schema_editor):
    DeploymentGuard = apps.get_model('guardmanagementsystem', 'DeploymentGuard')
    DeploymentGuard.objects.filter(status__in=['Active', 'Has No Deployment']).update(status='Available for Deployment')
    DeploymentGuard.objects.filter(status='On Deployment').update(status='On Site')


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0041_alter_deploymentguard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentguard',
            name='status',
            field=models.CharField(choices=[('Available for Deployment', 'Available for Deployment'), ('On Site', 'On Site'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Available for Deployment', max_length=30),
        ),
        migrations.RunPython(update_guard_deployment_status_labels, migrations.RunPython.noop),
    ]