# Generated by Django 6.0.1 on 2026-06-22 12:18

import django.db.models.deletion
from django.db import migrations, models


def copy_guard_rfid_cards_to_deployment_guards(apps, schema_editor):
    DeploymentGuard = apps.get_model('guardmanagementsystem', 'DeploymentGuard')
    Guard = apps.get_model('guardmanagementsystem', 'Guard')

    guard_card_ids = dict(
        Guard.objects.exclude(rfid_card_id__isnull=True).values_list('guard_id', 'rfid_card_id')
    )

    for assignment in DeploymentGuard.objects.filter(rfid_card_id__isnull=True).only(
        'deployment_guard_id', 'guard_id', 'rfid_card_id'
    ):
        card_id = guard_card_ids.get(assignment.guard_id)
        if card_id:
            assignment.rfid_card_id = card_id
            assignment.save(update_fields=['rfid_card'])


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0042_alter_deploymentguard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentguard',
            name='rfid_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_guard_assignments', to='guardmanagementsystem.rfidcard'),
        ),
        migrations.RunPython(copy_guard_rfid_cards_to_deployment_guards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='guard',
            name='rfid_card',
        ),
        migrations.RemoveField(
            model_name='guard',
            name='rfid_card_number',
        ),
    ]
