# Generated by Django 6.0.1 on 2026-06-22 12:30

from django.db import migrations, models


def copy_deployment_guard_cards_to_contracts(apps, schema_editor):
    DeploymentGuard = apps.get_model('guardmanagementsystem', 'DeploymentGuard')

    assignments = DeploymentGuard.objects.exclude(
        rfid_card_id__isnull=True
    ).exclude(
        deployment__contract_id__isnull=True
    ).select_related('deployment')

    for assignment in assignments.only('rfid_card_id', 'deployment__contract_id'):
        assignment.deployment.contract.rfid_cards.add(assignment.rfid_card_id)


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0043_remove_guard_rfid_card_remove_guard_rfid_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rfid_cards',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='guardmanagementsystem.rfidcard'),
        ),
        migrations.RunPython(copy_deployment_guard_cards_to_contracts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='deploymentguard',
            name='rfid_card',
        ),
    ]
