# Generated by Django 6.0.1 on 2026-06-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardmanagementsystem', '0044_remove_deploymentguard_rfid_card_contract_rfid_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='rfid_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard', to='guardmanagementsystem.rfidcard'),
        ),
    ]
